### ISSUE TITLE
Mamba-UNet vs. U-Mamba 

### ISSUE THREAD

**Issue by jizhang02** [ziyangwang007/Mamba-UNet#1]
Hello,

Interesting work! Coincidently, another work has a similar name (U-Mamba) as yours (Mamba-UNet):
https://github.com/bowang-lab/U-Mamba 
Do you have any similarities or differences?

Regards,
Jing

**Comment by ziyangwang007** [comment]
Hi,

In short, UMamba is based on Original Mamba, and our Mamba-UNet is based on Visual Mamba.

Here is the reference of Visual Mamba:
Liu, Yue, et al. "Vmamba: Visual state space model." arXiv preprint arXiv:2401.10166 (2024).
