### ISSUE TITLE
Torch and Cuda version not match

### ISSUE THREAD

**Issue by zero19970** [ziyangwang007/Mamba-UNet#13]
from torch._C import *  # noqa: F403
ImportError: .../python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: _ZNSt15__exception_ptreqERKNS_13exception_ptrES2_, version CXXABI_1.3.3

Neet torch version over 2.3.0?

**Comment by ziyangwang007** [comment]
hi could you check if PyTorch 1.12+ CUDA 11.6+
