### ISSUE TITLE
Mamba-v2，Mambav2-UNet？

### ISSUE THREAD

**Issue by GZ-YourZY** [ziyangwang007/Mamba-UNet#18]
I noticed that the Mamba-v2 architecture is currently generated. I would like to ask if you plan to provide this version of the UNet model.

**Comment by ziyangwang007** [comment]
I recently worked on using KAN-conv, and have no time with mamba2. Are you interested at it? Maybe we could discuss further. Happy to discuss with you on email. ziyang.wang17 [at] gmail [dot] com
