### ISSUE TITLE
VSSM

### ISSUE THREAD

**Issue by zhangfeifei1-ab** [ziyangwang007/Mamba-UNet#2]
I hope this message finds you well. I've been working with your  code, and I encountered an issue that I hope you can help me with. When attempting to run the code, I received a KeyError stating 'Non-existent config key: MODEL.VSSM'. Upon reviewing the code, I couldn't find any configurations related to VSSM.

Could you please guide me on how to resolve this issue? Is there a specific version of the code or additional configuration files that I should be using to include the VSSM settings?

Thank you in advance for your assistance. I appreciate your work on this project and look forward to your response

**Comment by ziyangwang007** [comment]
Thanks for your message. 

I also found this issue today after you mention this error. 

I have now fixed it. Please check the latest code from this github respository again.

**Comment by zhangfeifei1-ab** [comment]
thank you!

**Comment by geek-APTX4869** [comment]
> Thanks for your message.
> 
> I also found this issue today after you mention this error.
> 
> I have now fixed it. Please check the latest code from this github respository again.

Still has this issue, no fix
