### ISSUE TITLE
Image Size for Mamba-UNet and UNet

### ISSUE THREAD

**Issue by 2265103334** [ziyangwang007/Mamba-UNet#3]
Hello, Interesting work! I want to know the image size used to train Mamba-UNet and UNet, and the reproduced results are inconsistent with the paper. (image size : 256 * 256)
![image](https://github.com/ziyangwang007/Mamba-UNet/assets/158577863/226c1406-6dc2-423c-aa56-b1d003e95539)

**Comment by ziyangwang007** [comment]
Hi, thanks for your interest. Please have a look at Q&A 1 in the main page of this GitHub. I also like to discuss you in detail if you like through my email, see Q&A 5.
