### ISSUE TITLE
Are these the efficient people in the eyes of teachers?

### ISSUE THREAD

**Issue by Grozta** [ziyangwang007/Mamba-UNet#4]
You are working too fast. It only takes 2 weeks to do the work, and the results are huge.

**Comment by ziyangwang007** [comment]
Hi, thanks for your message. I just work day and night without having meal during Chunjie (roughly for 3 weeks). I lose weight 0.5kg per day during that time. I am not looking for a job at the current stage. I just feel so excited when I have a look at Mamba. and to be honest, I feel SwinUNet/TransUNet donot perform so good than UNet, but Mamba somehow at lease works..... BTW, I am also happy to discuss with you further with anything you like such as academic/life/code, or make friends. Please connect with me through email(see Q&A 5) if you like. :-) hope you have a good day.
