### ISSUE TITLE
val_2D_ViT.py

### ISSUE THREAD

**Issue by ZZUzyc** [ziyangwang007/Mamba-UNet#6]
hi! there seems to be a file missing : .. /code/val_2D_ViT.py

**Comment by Qu1n-22** [comment]
+1
But I think the file is val_2D.py
I use the file ，It runs for a minutes，and still wrong.
![Snipaste_2024-03-05_22-43-14](https://github.com/ziyangwang007/Mamba-UNet/assets/58621926/ad8152bd-0cde-49e9-92e7-4898b85e49e3)

**Comment by TatsuyaHasunuma0123** [comment]
Please Copy `val_2D.py` as `val_2D_ViT.py`.
And then , please refact test_single_volume like this.

```py
def test_single_volume(image, label, net, classes, patch_size=[224, 224]):
    image, label = (
        image.squeeze(0).cpu().detach().numpy(),
        label.squeeze(0).cpu().detach().numpy(),
    )
   ```

**Comment by ziyangwang007** [comment]
hi, sorry for late reply.  val_2D val_2D_ViT basically are same. because sometimes i use 256x256 for unet, and 224x224 for swinunet, so i use two different files.
