### ISSUE TITLE
what is model1 ？

### ISSUE THREAD

**Issue by Qu1n-22** [ziyangwang007/Mamba-UNet#7]
In the file 'train_Semi_Mamba_UNet.py'.
![image](https://github.com/ziyangwang007/Mamba-UNet/assets/58621926/cbdcca7f-06a4-4adf-a3b2-00336fb74ab6)

**Comment by Lizhuo97** [comment]
In the line 153-159 of the file 'train_Semi_Mamba_UNet.py'. 
I change "model2" to "model1" in the line 153 and 155. I am not sure if  this is correct, but the code works.

**Comment by ziyangwang007** [comment]
hi, please try model1 as unet, and model2 as mambaunet.

**Comment by liubaoning111** [comment]
I'm sorry, I don't quite follow you, do I?
