### ISSUE TITLE
If I want to use the base version of VMamba, how should I modify the code and which version of the pre-training file should I use?

### ISSUE THREAD

**Issue by InMyDreammer** [ziyangwang007/Mamba-UNet#8]
If I want to use the base version of VMamba, how should I modify the code and which version of the pre-training file should I use?

**Comment by ziyangwang007** [comment]
Hello. This question is beyond the scope of what I'm doing. But do have a look at official page of VMamba 'https://github.com/MzeroMiko/VMamba'.
